### ISSUE TITLE
Any update for ReactNative 60++  ?

### ISSUE THREAD

**Issue by arunraj-smartrabbitz** [erikpoort/react-native-cybersource-sdk#4]
Is there any update for latest ReactNative ver 60++ (68 atleast) ?
I couldnt find any helpful documentation to integrate this RN sdk. Is it recommended to refer the native methods and integrate it as native module ?

**Comment by erikpoort** [comment]
Hi! I am not maintaining this library anymore. Feel free to check out any of the [forks](https://github.com/erikpoort/react-native-cybersource-sdk/network/members), maybe someone else has a solution!

If you fork and fix it yourself, feel free to do a Pull request.
